---
engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
      global-require:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- tests/**/*
- app/conf.*
- build/
- app/user-modules/*/**/*
