sudo: required
language: node_js

services:
  - mongodb

node_js:
  - "0.12"
  - "4.0.0"
  - "4.2.6"
  - "5.5.0"
matrix:
  allow_failures:
    - node_js: 5.5.0
install:
  - ./build/install-openldap.sh
  - cp -v build/conf.app.js app/conf.js
  - cp -v build/conf.test.js tests/conf.js
  - npm install
  - node build/store.js

branches:
  only:
    - master

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#openmrs"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    use_notice: true
    skip_join: true

before_script:

script:
  - npm test
