sudo: required
dist: trusty
language: node_js
cache: yarn

services:
  - mongodb

node_js:
  - "4"
  - "5"

install:
  - ./build/install-openldap.sh
  - cp -v build/conf.app.js app/conf.js
  - cp -v build/conf.test.js tests/conf.js
  - npm install
  - node build/store.js

branches:
  only:
    - master

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#openmrs"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    use_notice: true
    skip_join: true

script:
  - npm test
