version: "2"
services:
  web:
    build:
      context: .
    container_name: "id_dashboard"
    restart: always
    links:
      - mongodb
  mongodb:
    image: frodenas/mongodb:2.6
    container_name: "id_dashboard_mongo"
    command: "--smallfiles"
    restart: always
