version: "2"
services:
  mongodb:
    image: frodenas/mongodb:2.6
    container_name: "id_dashboard_mongo"
  mailcatcher:
    image: jeanberu/mailcatcher
    container_name: "id_dashboard_mailcatcher"
  web:
    build:
      context: .
    depends_on:
      - mongodb
      - mailcatcher
    container_name: "id_dashboard"
