version: "2"
services:
  web:
    build:
      context: .
      ports:
        - "3000:3000"
  mongodb:
    image: frodenas/mongodb:2.6
    environment:
      - MONGODB_USERNAME=openmrsid
      - MONGODB_PASSWORD=changemetosomethingsecure
      - MONGODB_DBNAME=openmrsid
    ports:
      - "127.0.0.1:27018:27017"

    volumes:
      - ./docker/data/mongo:/data
