version: "2.1"

services:
  web:
    user: "${UID}:${GID}"
    env_file: .env
    build:
      context: .
    ports:
      - 0.0.0.0:3000:3000
    restart: unless-stopped
    depends_on:
      - mailcatcher
      - mongodb
      - openldap
    volumes:
      - .:/opt/id
    container_name: "id_dashboard"
  mongodb:
    image: mongo:3.2
    ports:
      - "0.0.0.0:27017:27017"
    container_name: "id_dashboard_mongo"
    volumes:
      - ./data/runtime/db:/data/db
      - ./data/dump:/dump
    restart: unless-stopped
    command: "mongod --nojournal --smallfiles"
  mailcatcher:
    image: jeanberu/mailcatcher
    ports:
      - "0.0.0.0:1080:1080"
      - "0.0.0.0:1025:1025"
    container_name: "id_dashboard_mailcatcher"
  openldap:
    image: osixia/openldap:1.1.7
    environment:
      - LDAP_TLS=false
    volumes:
      - ./data/ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d
      - ./data/ldap/var/lib/ldap:/var/lib/ldap
    ports:
      - 127.0.0.1:389:389
    container_name: "id_dashboard_openldap"
