version: "2.1"
services:
  web:
    image: openmrs/id:latest
    container_name: "id_dashboard"
    env_file: .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      mongodb:
          condition: service_healthy
      openldap:
          condition: service_started
    volumes:
      - ./data/globalnavbar:/opt/id/app/user-modules/openmrs-contrib-id-globalnavbar/data
      - ./data/logs:/opt/id/logs
  mongodb:
    image: mongo:3.4
    container_name: "id_dashboard_mongo"
    command: mongod --smallfiles
    restart: unless-stopped
    volumes:
      - ./data/mongo/db:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "localhost/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 1)';"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  openldap:
    image: osixia/openldap:1.1.8
    container_name: "id_dashboard_openldap"
    ports:
      - 127.0.0.1:389:389
      - 127.0.0.1:636:636
    environment:
      - LDAP_LOG_LEVEL=0
    volumes:
      - ./data/ldap/config:/etc/ldap/slapd.d
      - ./data/ldap/database:/var/lib/ldap
      - ./data/ldap/certs/:/container/service/slapd/assets/certs/
    restart: unless-stopped
