version: "2.1"
services:
  web:
    build:
      context: .
    container_name: "id_dashboard"
    env_file: .env
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - mongodb
      - openldap
    volumes:
      - ./data/globalnavbar:/opt/id/app/user-modules/openmrs-contrib-id-globalnavbar/data
  mongodb:
    image: mongo:3.4
    container_name: "id_dashboard_mongo"
    command: mongod --smallfiles
    restart: always
    volumes:
      - ./data/mongo/db:/data/db
  openldap:
    image: osixia/openldap:1.1.7
    environment:
      - LDAP_TLS=false
    volumes:
      - ./data/ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d
      - ./data/ldap/var/lib/ldap:/var/lib/ldap
    restart: always
    ports:
      - 127.0.0.1:389:389
    container_name: "id_dashboard_openldap"
