version: "2"
services:
  mongodb:
    image: mongo:2.6
    container_name: "id_dashboard_mongo"
    command: mongod --smallfiles
  mailcatcher:
    image: jeanberu/mailcatcher
    container_name: "id_dashboard_mailcatcher"
  web:
    build:
      context: .
    depends_on:
      - mongodb
      - mailcatcher
    container_name: "id_dashboard"
